### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sosie-js**
baby is wet when no args is given, prevent this

### CODE REVIEW

**Comment by gvvaughan** [comment]
Thanks again for your PR, very much appreciated!

I'm not keen on applying this one for two reasons:
1. `nil` valued _G.arg doesn't really happen AFAICT
2. the README is trying to give simple instructions for straight forward use, if a user somehow manages to run an option parser inside a sandbox with no _G.arg, then it makes no sense to be running an option parser anyway!

What am I failing to understand?

```sh
$ lua                                                 
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
> for k, v in next, _G.arg do print(k, v) end
0	lua
```

**Comment by sosie-js** [comment]
Hello Gary,

When no args is given , normal behavior is for example to display the help or an error "This command requires arguments, to see them type <command> --h or --help" . This is a dummy failback, it can be an other such a call to an hidden feature creating an ENV or needing no display like doing a refresh of internal calculations where the result is not saved to stdout. These are just a suggestions to help the end user not be disturbed or lost by the crashing error.

It was just for your information. I close the PR.

**Comment by sosie-js** [comment]
>What am I failing to understand?

>$ lua                                                 
>Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
> for k, v in next, _G.arg do print(k, v) end
>0	lua
I did not respond to this, when you pass some args to your programs, then you see them with this code.
and then you know how to bridge keys with functions that do the real job behind aka in backoffice.
I reopen it if you want comment.

**Comment by sosie-js** [comment]
My PR is wrong I have to fix it because my comment "add your parser:on(..) stuff " is not in good place, it should have been
```lua 
local parser = OptionParser (help)
--add your parser:on(..) stuff 
parser:on('--giveakiss', parser.optional, parser.boolean)

if _G.arg ~= nil then
   local arg, opts = parser:parse (_G.arg)
   --Just a dump to see you can check if the baby listened what you told him
   for x, v in pairs(opts) do 
       --Do the real backoffice work  according to key x matching option name and v matching option value 
       --print(x, v) 
       if x == "giveakiss" then
             if(v) then
                 print("Baby happy")
            else
                 print("Baby sad")
            end
        end
    end
else
  --Give some hint incitating user to provide options args
   help()
end
```
. I did not realize what you want to express . Thank you.

**Comment by gvvaughan** [comment]
But I still don't understand how _G.arg can be `nil` valued, so that condition is never satisfied (unless you carefully sandbox it to wipe out the arg entry in the global table)?  Under normal circumstances, at the very least we'll have `_G.arg[0] == 'lua'` (or similar).

Are you saying that you want to write an optspec that requires arguments, but when no arguments are given instead of showing the usage message it does something else?  Wouldn't it be better to write the optspec with no required arguments in that case, and then processing will continue silently as specified when no arguments are passed.

**Comment by sosie-js** [comment]
I can't reproduce the case wonder how I achieve to have nil during the integration of code. 
I use scite to develop but F5 is just a shorcut to lua5.1 -u code.lua so indeed _G.arg[0] is code.lua so not nil.
Now if I understand what you said for the optspec, as it is already optional,
```lua
  noargsprocessed=true
   for x, v in pairs(opts) do 
       --Do the real backoffice work  according to key x matching option name and v matching option value 
       --print(x, v) 
       if x == "giveakiss" then
            noargsprocessed=false
             if(v) then
                 print("Baby happy")
            else
                 print("Baby sad")
            end
        end
    end
 if(noargsprocessed) then
  --Give some hint incitating user to provide options args
   help()
end
```
`

**Comment by gvvaughan** [comment]
I mean that if you write an optspec that requires some command line arguments then when you call `local arg, opts = parser:parse (_G.arg)` without any arguments, the `parser:parse` call will already write a diagnostic error that gives you a brief usage message including how to use `--help` to get more help.  If you write an optspec that does not require any command line arguments, then when you call `parser:parse` it will process the zero arguments given, and then continue silently.

**Comment by sosie-js** [comment]
I don't know how to do this I don't want spend more time on it as it it not important. I am new in lua, I don't know to handle optspecs as your describe , what i see in specs/ directory is an other language to learn. Have a good day.

**Comment by gvvaughan** [comment]
No worries.  Thanks for the PR and discussion!  For the record, I wasn't asking you to do anything... I'm saying that there's nothing to be done here because when using this library, you can either require arguments or have all optional arguments and the existing implementation will already handle those cases out of the box, because _G.arg can only ever be `nil` if you deliberately overwrite it somehow.

**Pull request closed without merging**
